channels:
- conda-forge
dependencies:
- pyiron_base =0.5.2
- damask =3.0.0a5
- fenics =2019.1.0
- matplotlib
- mshr =2019.1.0
- panel =0.12.6
- pyiron-data >=0.0.17
- pyvista
- scipy
- seaborn
- pyprecice=2.3.0.1
- pip
- pip:
      - git+https://github.com/precice/fenics-adapter.git
